[server]
runOnSave = true
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false
maxMessageSize = 200
enableWebsocketCompression = true

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = false 